name = "Underpunks: Create Takes Flight"
author = "Forsak3nBacon"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d234b149c1e2dde31dca272c4ffd07d6a3ac4838f22d59b1b0e006fd80a6797"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
