name = "Underpunks: Create Takes Flight"
author = "Forsak3nBacon"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad071b349f47f6be54daa469c915a95d0f13bb4dafd462eb4327aa2744226cc6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
