name = "Underpunks: The Create Age"
author = "Forsak3nBacon"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c82ed2154cd60c2e39f22903f37c97f0ecf23fc3e5841ad35e01e64749a8d492"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
